<?php

/** @var $block \Magenest\CustomerChatbox\Block\FacebookMessenger * */
$customerChatboxHelperData = $this->helper('Magenest\CustomerChatbox\Helper\Data');
?>
<!-- Facebook Messenger -->
<?php if ($customerChatboxHelperData->getFacebookMessengerStatus()): ?>
    <script>
        window.fbAsyncInit = function() {
            FB.init({
                xfbml            : true,
                version          : 'v8.0'
            });
        };

        (function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = 'https://connect.facebook.net/en_US/sdk/xfbml.customerchat.js';
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>

    <!-- Your customer chat code -->
    <?= $customerChatboxHelperData->getFacebookMessengerChatCode(); ?>
<?php endif; ?>
<!-- End Facebook Messenger -->

